language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
install:
  - composer install --prefer-dist -o -n -d src/<%= pluginHandle.toLowerCase() %>
  - composer install --prefer-dist -o -n -d src/tests
script:
  - ./src/tests/vendor/bin/phpunit --configuration ./src/tests/phpunit.xml
